// Comprehensive list of 120+ writing genres organized by categories
// From the user's extensive list of genres

export const GENRE_CATEGORIES = {
  "General Fiction": [
    "fiction",
    "drama",
    "literary fiction",
    "political fiction",
    "musical fiction",
    "sports fiction",
    "suspense fiction"
  ],
  "Science Fiction": [
    "science fiction",
    "cyberpunk",
    "dystopian",
    "post-apocalyptic",
    "steampunk",
    "dieselpunk",
    "nanopunk",
    "solarpunk",
    "atompunk",
    "clockpunk",
    "postcyberpunk",
    "utopian",
    "comedy sci-fi",
    "feminist sci-fi",
    "gothic sci-fi",
    "climate fiction",
    "parallel world sci-fi",
    "libertarian sci-fi",
    "mecha sci-fi",
    "military sci-fi",
    "social sci-fi",
    "anthropological sci-fi",
    "space opera",
    "space western",
    "subterranean sci-fi",
    "tech noir",
    "alien invasion",
    "scientific romance",
    "dying earth",
    "quantum fiction"
  ],
  "Fantasy": [
    "fantasy",
    "contemporary fantasy",
    "cozy fantasy",
    "dark fantasy",
    "high fantasy",
    "fantasy comedy",
    "gothic fantasy",
    "historical fantasy",
    "low fantasy",
    "mythpunk",
    "mythic fantasy",
    "mythopoeia",
    "magic realism",
    "romantic fantasy",
    "science fantasy",
    "supernatural fantasy",
    "heroic fantasy",
    "portal fantasy",
    "medieval fantasy",
    "prehistoric fantasy"
  ],
  "Horror": [
    "horror",
    "comedy horror",
    "gothic horror",
    "zombie horror",
    "dark romanticism",
    "cosmic horror",
    "werewolf fiction",
    "vampire literature",
    "psychological horror",
    "techno-horror",
    "apocalyptic",
    "zombie apocalypse",
    "monster literature",
    "weird fiction"
  ],
  "Mystery & Crime": [
    "mystery",
    "crime fiction",
    "detective",
    "historical mystery",
    "noir",
    "cozy mystery",
    "legal thriller",
    "caper",
    "spy fiction"
  ],
  "Thriller": [
    "thriller",
    "psychological thriller",
    "techno-thriller",
    "political thriller"
  ],
  "Romance": [
    "romance",
    "paranormal romance",
    "contemporary romance",
    "medical romance",
    "thriller romance",
    "historical romance",
    "inspirational romance",
    "romantic suspense",
    "western romance",
    "young adult romance",
    "chivalric romance"
  ],
  "Western": [
    "western",
    "horror western",
    "science fiction western",
    "weird western",
    "fantasy western"
  ],
  "Young Adult & New Adult": [
    "young adult",
    "new adult"
  ],
  "Historical": [
    "historical fiction",
    "prehistoric fiction",
    "medieval fiction"
  ],
  "Comedy": [
    "comedy",
    "tragic comedy",
    "burlesque"
  ],
  "Drama": [
    "tragedy",
    "melodrama"
  ],
  "Superhero": [
    "superhero fantasy",
    "cape punk",
    "heroic noir"
  ],
  "Speculative & Experimental": [
    "xenofiction",
    "alternative history",
    "slipstream",
    "postmodern",
    "conte",
    "pulp fiction"
  ],
  "Action & Adventure": [
    "action-adventure",
    "nautical"
  ]
};

export const ALL_GENRES = Object.values(GENRE_CATEGORIES).flat();

export const GENDER_IDENTITIES = [
  "male",
  "female", 
  "non-binary",
  "agender",
  "bigender",
  "genderfluid",
  "genderqueer",
  "transgender",
  "intersex",
  "pangender",
  "demigender",
  "androgynous",
  "omnigender",
  "polygender"
];

// Comprehensive list of setting types organized by categories
export const SETTING_TYPE_CATEGORIES = {
  "Geographic Regions": [
    "world",
    "country",
    "state/province", 
    "county",
    "city",
    "town",
    "village",
    "settlement",
    "kingdom",
    "empire",
    "realm",
    "ghost town",
    "abandoned city",
    "lost city"
  ],
  "Natural Environments": [
    "forest",
    "mountain range",
    "desert",
    "field",
    "meadow",
    "river",
    "lake",
    "waterfall",
    "oasis",
    "garden",
    "canyon",
    "ridge",
    "spring",
    "cliff",
    "crater",
    "ocean",
    "bay",
    "beach",
    "island",
    "archipelagos",
    "cave",
    "lagoon",
    "national park",
    "reservoir",
    "dunes",
    "valley",
    "rainforest",
    "savannah",
    "grassland",
    "bog",
    "swamp",
    "tar pit",
    "marshland",
    "glacier",
    "hot springs",
    "geyser",
    "Everglades",
    "estuary",
    "cove",
    "grove",
    "glen",
    "animal pasture",
    "trail",
    "causeway"
  ],
  "Residential Buildings": [
    "house",
    "apartment",
    "condo",
    "cabin",
    "townhouse",
    "mansion",
    "cottage",
    "villa",
    "apartment building",
    "condo building",
    "trailer",
    "camper van",
    "caravan"
  ],
  "Commercial Establishments": [
    "restaurant",
    "store",
    "mall",
    "bookstore",
    "department store",
    "hardware store",
    "bank",
    "pharmacy",
    "bar",
    "tavern",
    "pub",
    "diner",
    "coffee shop",
    "fast food restaurant",
    "juice bar",
    "karaoke bar",
    "lounge",
    "dance club",
    "brothel",
    "marketplace",
    "farmer's market",
    "market stall",
    "food truck",
    "furniture store",
    "antique shop",
    "gift shop",
    "toy store",
    "clothing store",
    "boutique",
    "consignment shop",
    "bodega",
    "convenience store",
    "dollar store",
    "electronics store",
    "fabric store",
    "outlet",
    "liquor store",
    "florist",
    "fish market",
    "food court",
    "deli",
    "butcher shop",
    "bakery",
    "ice cream shop",
    "pizza shop",
    "sandwich shop",
    "game store",
    "gas station",
    "mechanic shop",
    "car dealership",
    "car wash",
    "hobby store",
    "jewelry store",
    "music store",
    "camera store",
    "candy shop",
    "emporium",
    "general store",
    "feed store",
    "pet store",
    "outlet store",
    "drive-thru",
    "Internet cafe",
    "real estate agency",
    "retailer",
    "sausage stand"
  ],
  "Public & Government Buildings": [
    "library",
    "community centre",
    "civic centre",
    "city hall",
    "government building",
    "parliament building",
    "courthouse",
    "court room",
    "police station",
    "fire hall",
    "fire department",
    "fire station",
    "post office",
    "embassy",
    "immigration centre",
    "information centre",
    "convention centre",
    "print shop",
    "town square",
    "trade centre"
  ],
  "Entertainment Venues": [
    "movie theatre",
    "cinema",
    "theatre",
    "drive-in theatre",
    "opera house",
    "arena",
    "stadium",
    "aquarium",
    "arcade",
    "amusement park",
    "water park",
    "playground",
    "carnival",
    "festival",
    "fair",
    "circus",
    "colosseum",
    "boardwalk",
    "casino",
    "roller rink",
    "jazz club",
    "speak easy",
    "concert hall",
    "amphitheatre",
    "concert",
    "music festival",
    "concession stand"
  ],
  "Transportation & Infrastructure": [
    "airport",
    "terminal",
    "bus stop",
    "highway",
    "road",
    "street",
    "crescent",
    "bridge",
    "pier",
    "harbour",
    "wharf",
    "marina",
    "garage",
    "parking garage",
    "railway",
    "subway",
    "speedway",
    "arch",
    "gateway",
    "dam",
    "lighthouse",
    "tower",
    "clock tower",
    "quay"
  ],
  "Religious & Spiritual Buildings": [
    "church",
    "chapel",
    "cathedral",
    "mosque",
    "shrine",
    "pyramid",
    "monastery"
  ],
  "Educational Institutions": [
    "school",
    "college",
    "university",
    "high school",
    "elementary school",
    "middle school",
    "boarding school",
    "campus",
    "classroom"
  ],
  "Healthcare Facilities": [
    "hospital",
    "clinic",
    "medical centre",
    "infirmary",
    "emergency room",
    "hospital room",
    "operating room",
    "doctor's office",
    "dentist",
    "optometrist",
    "chiropractor",
    "orthodontist",
    "physiotherapist",
    "massage therapist",
    "wellness centre"
  ],
  "Sports & Recreation": [
    "gym",
    "pool",
    "racetrack",
    "sports field",
    "aquatic centre",
    "recreation centre",
    "martial arts studio",
    "dance studio",
    "baseball diamond",
    "ice rink",
    "tennis court",
    "basketball court"
  ],
  "Industrial & Agricultural": [
    "factory",
    "warehouse",
    "farm",
    "farmhouse",
    "vineyard",
    "barn",
    "granary",
    "silo",
    "mine",
    "quarry",
    "oil rig",
    "mill",
    "lumberyard",
    "dump",
    "recycling depot",
    "junkyard",
    "abattoir",
    "sand pit",
    "gravel pit"
  ],
  "Vehicles & Mobile Settings": [
    "space station",
    "rocket ship",
    "pirate ship",
    "caravan",
    "trailer",
    "camper van",
    "food truck"
  ],
  "Interior Spaces": [
    "room",
    "kitchen",
    "bedroom",
    "living room",
    "bathroom",
    "boardroom",
    "office",
    "basement",
    "cellar",
    "balcony",
    "hall",
    "dining hall",
    "cafeteria",
    "dorm room",
    "vault",
    "dungeon",
    "prison"
  ],
  "Personal Care & Services": [
    "salon",
    "barber's shop",
    "spa",
    "nail salon",
    "hair salon",
    "saloon",
    "bathhouse",
    "laundromat"
  ],
  "Cultural & Arts": [
    "museum",
    "art gallery",
    "gallery",
    "auditorium",
    "studio",
    "production studio",
    "television set",
    "movie set",
    "recording studio",
    "radio station",
    "orchestra pit"
  ],
  "Military & Historical": [
    "castle",
    "barracks",
    "army base",
    "battlefield",
    "camp",
    "monument",
    "memorial",
    "cemetery",
    "wall",
    "barrier"
  ],
  "Specialized Buildings": [
    "apothecary",
    "blacksmith forge",
    "crematorium",
    "morgue",
    "funeral home",
    "aviary",
    "zoological park",
    "nursery",
    "space centre",
    "lawyer's chambers",
    "landmark",
    "hotel",
    "hostel",
    "motel",
    "bed and breakfast",
    "inn",
    "bistro",
    "brewery",
    "palace",
    "sky deck"
  ],
  "Celestial & Fantastical": [
    "planet",
    "realm"
  ]
};

export const ALL_SETTING_TYPES = Object.values(SETTING_TYPE_CATEGORIES).flat();