// Comprehensive list of 120+ writing genres organized by categories
// From the user's extensive list of genres

export const GENRE_CATEGORIES = {
  "General Fiction": [
    "Fiction",
    "Drama",
    "Literary Fiction",
    "Political Fiction",
    "Musical Fiction",
    "Sports Fiction",
    "Suspense Fiction"
  ],
  "Science Fiction": [
    "Science Fiction",
    "Cyberpunk",
    "Dystopian",
    "Post-Apocalyptic",
    "Steampunk",
    "Dieselpunk",
    "Nanopunk",
    "Solarpunk",
    "Atompunk",
    "Clockpunk",
    "Postcyberpunk",
    "Utopian",
    "Comedy Sci-Fi",
    "Feminist Sci-Fi",
    "Gothic Sci-Fi",
    "Climate Fiction",
    "Parallel World Sci-Fi",
    "Libertarian Sci-Fi",
    "Mecha Sci-Fi",
    "Military Sci-Fi",
    "Social Sci-Fi",
    "Anthropological Sci-Fi",
    "Space Opera",
    "Space Western",
    "Subterranean Sci-Fi",
    "Tech Noir",
    "Alien Invasion",
    "Scientific Romance",
    "Dying Earth",
    "Quantum Fiction"
  ],
  "Fantasy": [
    "Fantasy",
    "Contemporary Fantasy",
    "Cozy Fantasy",
    "Dark Fantasy",
    "High Fantasy",
    "Fantasy Comedy",
    "Gothic Fantasy",
    "Historical Fantasy",
    "Low Fantasy",
    "Mythpunk",
    "Mythic Fantasy",
    "Mythopoeia",
    "Magic Realism",
    "Romantic Fantasy",
    "Science Fantasy",
    "Supernatural Fantasy",
    "Heroic Fantasy",
    "Portal Fantasy",
    "Medieval Fantasy",
    "Prehistoric Fantasy"
  ],
  "Horror": [
    "Horror",
    "Comedy Horror",
    "Gothic Horror",
    "Zombie Horror",
    "Dark Romanticism",
    "Cosmic Horror",
    "Werewolf Fiction",
    "Vampire Literature",
    "Psychological Horror",
    "Techno-Horror",
    "Apocalyptic",
    "Zombie Apocalypse",
    "Monster Literature",
    "Weird Fiction"
  ],
  "Mystery & Crime": [
    "Mystery",
    "Crime Fiction",
    "Detective",
    "Historical Mystery",
    "Noir",
    "Cozy Mystery",
    "Legal Thriller",
    "Caper",
    "Spy Fiction"
  ],
  "Thriller": [
    "Thriller",
    "Psychological Thriller",
    "Techno-Thriller",
    "Political Thriller"
  ],
  "Romance": [
    "Romance",
    "Paranormal Romance",
    "Contemporary Romance",
    "Medical Romance",
    "Thriller Romance",
    "Historical Romance",
    "Inspirational Romance",
    "Romantic Suspense",
    "Western Romance",
    "Young Adult Romance",
    "Chivalric Romance"
  ],
  "Western": [
    "Western",
    "Horror Western",
    "Science Fiction Western",
    "Weird Western",
    "Fantasy Western"
  ],
  "Young Adult & New Adult": [
    "Young Adult",
    "New Adult"
  ],
  "Historical": [
    "Historical Fiction",
    "Prehistoric Fiction",
    "Medieval Fiction"
  ],
  "Comedy": [
    "Comedy",
    "Tragic Comedy",
    "Burlesque"
  ],
  "Drama": [
    "Tragedy",
    "Melodrama"
  ],
  "Superhero": [
    "Superhero Fantasy",
    "Cape Punk",
    "Heroic Noir"
  ],
  "Speculative & Experimental": [
    "Xenofiction",
    "Alternative History",
    "Slipstream",
    "Postmodern",
    "Conte",
    "Pulp Fiction"
  ],
  "Action & Adventure": [
    "Action-Adventure",
    "Nautical"
  ]
};

export const ALL_GENRES = Object.values(GENRE_CATEGORIES).flat();

export const GENDER_IDENTITIES = [
  "Male",
  "Female", 
  "Non-Binary",
  "Agender",
  "Bigender",
  "Genderfluid",
  "Genderqueer",
  "Transgender",
  "Intersex",
  "Pangender",
  "Demigender",
  "Androgynous",
  "Omnigender",
  "Polygender"
];

// Comprehensive list of setting types organized by categories
export const SETTING_TYPE_CATEGORIES = {
  "Geographic Regions": [
    "World",
    "Country",
    "State/Province", 
    "County",
    "City",
    "Town",
    "Village",
    "Settlement",
    "Kingdom",
    "Empire",
    "Realm",
    "Ghost Town",
    "Abandoned City",
    "Lost City",
    "District",
    "Faction"
  ],
  "Natural Environments": [
    "Forest",
    "Mountain Range",
    "Desert",
    "Field",
    "Meadow",
    "River",
    "Lake",
    "Waterfall",
    "Oasis",
    "Garden",
    "Canyon",
    "Ridge",
    "Spring",
    "Cliff",
    "Crater",
    "Ocean",
    "Bay",
    "Beach",
    "Island",
    "Archipelagos",
    "Cave",
    "Lagoon",
    "National Park",
    "Reservoir",
    "Dunes",
    "Valley",
    "Rainforest",
    "Savannah",
    "Grassland",
    "Bog",
    "Swamp",
    "Tar Pit",
    "Marshland",
    "Glacier",
    "Hot Springs",
    "Geyser",
    "Everglades",
    "Estuary",
    "Cove",
    "Grove",
    "Glen",
    "Animal Pasture",
    "Trail",
    "Causeway",
    "Pond",
    "Salt Flats",
    "Tundra",
    "Wasteland",
    "Badlands",
    "Wildlife Reserve",
    "Cavern",
    "Lair",
    "Orchard",
    "Grotto",
    "Haunted Woods"
  ],
  "Residential Buildings": [
    "House",
    "Apartment",
    "Condo",
    "Cabin",
    "Townhouse",
    "Mansion",
    "Cottage",
    "Villa",
    "Apartment Building",
    "Condo Building",
    "Trailer",
    "Camper Van",
    "Caravan"
  ],
  "Commercial Establishments": [
    "Restaurant",
    "Store",
    "Mall",
    "Bookstore",
    "Department Store",
    "Hardware Store",
    "Bank",
    "Pharmacy",
    "Bar",
    "Tavern",
    "Pub",
    "Diner",
    "Coffee Shop",
    "Fast Food Restaurant",
    "Juice Bar",
    "Karaoke Bar",
    "Lounge",
    "Dance Club",
    "Brothel",
    "Marketplace",
    "Farmer's Market",
    "Market Stall",
    "Food Truck",
    "Furniture Store",
    "Antique Shop",
    "Gift Shop",
    "Toy Store",
    "Clothing Store",
    "Boutique",
    "Consignment Shop",
    "Bodega",
    "Convenience Store",
    "Dollar Store",
    "Electronics Store",
    "Fabric Store",
    "Outlet",
    "Liquor Store",
    "Florist",
    "Fish Market",
    "Food Court",
    "Deli",
    "Butcher Shop",
    "Bakery",
    "Ice Cream Shop",
    "Pizza Shop",
    "Sandwich Shop",
    "Game Store",
    "Gas Station",
    "Mechanic Shop",
    "Car Dealership",
    "Car Wash",
    "Hobby Store",
    "Jewelry Store",
    "Music Store",
    "Camera Store",
    "Candy Shop",
    "Emporium",
    "General Store",
    "Feed Store",
    "Pet Store",
    "Outlet Store",
    "Drive-Thru",
    "Internet Cafe",
    "Real Estate Agency",
    "Retailer",
    "Sausage Stand",
    "Grocery Store",
    "Supermarket",
    "Tailor",
    "Tanning Salon",
    "Tax Advisor",
    "Tea House",
    "Tea Room",
    "Thrift Store",
    "Travel Agency",
    "Wig Store",
    "Upholstery Shop",
    "Technology Company",
    "Catering Company",
    "Commercial Kitchen",
    "Strip Club"
  ],
  "Public & Government Buildings": [
    "Library",
    "Community Centre",
    "Civic Centre",
    "City Hall",
    "Government Building",
    "Parliament Building",
    "Courthouse",
    "Court Room",
    "Police Station",
    "Fire Hall",
    "Fire Department",
    "Fire Station",
    "Post Office",
    "Embassy",
    "Immigration Centre",
    "Information Centre",
    "Convention Centre",
    "Print Shop",
    "Town Square",
    "Trade Centre",
    "Forbidden City",
    "Government Agency",
    "Intelligence Agency",
    "News Station",
    "Refugee Centre"
  ],
  "Entertainment Venues": [
    "movie theatre",
    "cinema",
    "theatre",
    "drive-in theatre",
    "opera house",
    "arena",
    "stadium",
    "aquarium",
    "arcade",
    "amusement park",
    "water park",
    "playground",
    "carnival",
    "festival",
    "fair",
    "circus",
    "colosseum",
    "boardwalk",
    "casino",
    "roller rink",
    "jazz club",
    "speak easy",
    "concert hall",
    "amphitheatre",
    "concert",
    "music festival",
    "concession stand",
    "jousting arena",
    "gala",
    "rodeo",
    "bowling alley",
    "indoor playground"
  ],
  "Transportation & Infrastructure": [
    "airport",
    "terminal",
    "bus stop",
    "highway",
    "road",
    "street",
    "crescent",
    "bridge",
    "pier",
    "harbour",
    "wharf",
    "marina",
    "garage",
    "parking garage",
    "railway",
    "subway",
    "speedway",
    "arch",
    "gateway",
    "dam",
    "lighthouse",
    "tower",
    "clock tower",
    "quay",
    "seaport",
    "walkway",
    "train station",
    "tram station",
    "truck stop",
    "union station",
    "raceway",
    "breezeway",
    "turnpike",
    "intersection",
    "shipping yard"
  ],
  "Religious & Spiritual Buildings": [
    "church",
    "chapel",
    "cathedral",
    "mosque",
    "shrine",
    "pyramid",
    "monastery",
    "abbey"
  ],
  "Educational Institutions": [
    "school",
    "college",
    "university",
    "high school",
    "elementary school",
    "middle school",
    "boarding school",
    "campus",
    "classroom",
    "academy",
    "daycare",
    "computer lab"
  ],
  "Healthcare Facilities": [
    "hospital",
    "clinic",
    "medical centre",
    "infirmary",
    "emergency room",
    "hospital room",
    "operating room",
    "doctor's office",
    "dentist",
    "optometrist",
    "chiropractor",
    "orthodontist",
    "physiotherapist",
    "massage therapist",
    "wellness centre",
    "trauma centre",
    "acupuncturist",
    "naturopath"
  ],
  "Sports & Recreation": [
    "gym",
    "pool",
    "racetrack",
    "sports field",
    "aquatic centre",
    "recreation centre",
    "martial arts studio",
    "dance studio",
    "baseball diamond",
    "ice rink",
    "tennis court",
    "basketball court",
    "ski hill",
    "lodge",
    "resort",
    "campground",
    "trailer park",
    "dojo",
    "fighting ring",
    "boxing ring",
    "wrestling ring",
    "curling club",
    "lawn bowling club",
    "gymnastics club",
    "hockey arena"
  ],
  "Industrial & Agricultural": [
    "factory",
    "warehouse",
    "farm",
    "farmhouse",
    "vineyard",
    "barn",
    "granary",
    "silo",
    "mine",
    "quarry",
    "oil rig",
    "mill",
    "lumberyard",
    "dump",
    "recycling depot",
    "junkyard",
    "abattoir",
    "sand pit",
    "gravel pit",
    "slaughter house",
    "ranch",
    "corral",
    "bunkhouse",
    "lumber mill",
    "sawmill",
    "forge",
    "refinery"
  ],
  "Vehicles & Mobile Settings": [
    "space station",
    "rocket ship",
    "pirate ship",
    "caravan",
    "trailer",
    "camper van",
    "food truck",
    "submarine",
    "naval ship",
    "house boat",
    "zeppelin",
    "sunken ship",
    "cruise ship",
    "barge",
    "vessel",
    "sailboat",
    "yacht",
    "train car",
    "spaceship",
    "merchant ship",
    "shipping container",
    "helicopter"
  ],
  "Interior Spaces": [
    "room",
    "kitchen",
    "bedroom",
    "living room",
    "bathroom",
    "boardroom",
    "office",
    "basement",
    "cellar",
    "balcony",
    "hall",
    "dining hall",
    "cafeteria",
    "dorm room",
    "vault",
    "dungeon",
    "prison",
    "courtyard",
    "sunroom",
    "prison cell",
    "jail cell",
    "detainment unit",
    "cubicle",
    "chamber",
    "quarters",
    "workshop",
    "dormitory",
    "dining room",
    "attic"
  ],
  "Personal Care & Services": [
    "salon",
    "barber's shop",
    "spa",
    "nail salon",
    "hair salon",
    "saloon",
    "bathhouse",
    "laundromat",
    "pottery studio"
  ],
  "Cultural & Arts": [
    "museum",
    "art gallery",
    "gallery",
    "auditorium",
    "studio",
    "production studio",
    "television set",
    "movie set",
    "recording studio",
    "radio station",
    "orchestra pit"
  ],
  "Military & Historical": [
    "castle",
    "barracks",
    "army base",
    "battlefield",
    "camp",
    "monument",
    "memorial",
    "cemetery",
    "wall",
    "barrier",
    "tomb",
    "gravesite",
    "graveyard",
    "crypt",
    "underground bunker",
    "nuclear bunker",
    "barricade",
    "military park",
    "crash site",
    "ancient ruins",
    "gallows",
    "plantation"
  ],
  "Specialized Buildings": [
    "apothecary",
    "blacksmith forge",
    "crematorium",
    "morgue",
    "funeral home",
    "aviary",
    "zoological park",
    "nursery",
    "space centre",
    "lawyer's chambers",
    "landmark",
    "hotel",
    "hostel",
    "motel",
    "bed and breakfast",
    "inn",
    "bistro",
    "brewery",
    "palace",
    "sky deck",
    "hangar",
    "storage facility",
    "rocket centre",
    "launchpad",
    "fishing hut",
    "watch tower",
    "water tower",
    "research centre",
    "research lab",
    "nuclear power plant",
    "nuclear launch site",
    "wax museum",
    "boathouse",
    "botanical gardens",
    "pavilion",
    "pergola",
    "pagoda",
    "research station",
    "observatory",
    "treehouse",
    "bell tower",
    "stable",
    "haunted house"
  ],
  "Celestial & Fantastical": [
    "planet",
    "realm",
    "satellite",
    "star",
    "galaxy",
    "portal"
  ]
};

export const CREATURE_TYPE_CATEGORIES = {
  "Real Animals - Vertebrates": [
    "Fish", "Mammal", "Bird", "Amphibian", "Reptile", "Canine", "Feline", 
    "Aquatic Mammal", "Avian", "Primate", "Rodent", "Ungulate", "Bovine", 
    "Camelid", "Caprid", "Equine", "Pachyderm", "Swine", "Marsupial"
  ],
  "Real Animals - Invertebrates": [
    "Arthropod", "Crustacean", "Arachnid", "Mollusc", "Xenarthran"
  ],
  "Specialized Animal Types": [
    "Musteloid", "Herpestoid", "Procyonid", "Jackalope"
  ],
  "Fantasy Creatures": [
    "Dragon", "Unicorn", "Griffin", "Hypogriff", "Pegasus", "Phoenix"
  ],
  "Mythological Beings": [
    "Fairy", "Pixie", "Nymph", "Siren", "Sprite", "Dryad", "Druid", 
    "Valkyrie", "Banshee"
  ],
  "Shapeshifters & Lycanthropes": [
    "Werewolf", "Werehyena", "Wendigo", "Selkie", "Kelpie"
  ],
  "Undead & Supernatural": [
    "Vampire", "Wraith", "Ghoul", "Skeleton", "Draugr"
  ],
  "Humanoid Races": [
    "Elf", "Dwarf", "Gnome", "Goblin", "Humanoid"
  ],
  "Giants & Large Beings": [
    "Troll", "Ogre", "Giant", "Cyclops", "Minotaur"
  ],
  "Hybrid Creatures": [
    "Centaur", "Mermaid", "Faun", "Sphinx"
  ],
  "Constructed Beings": [
    "Golem", "Gargoyle", "Elemental"
  ],
  "Cryptids & Legendary": [
    "chupacabra", "yeti", "sasquatch", "kraken", "leviathan"
  ],
  "Serpentine & Reptilian": [
    "serpent", "basilisk", "gorgon", "hydra", "echidna", "sea serpent"
  ],
  "Spirits & Ethereal": [
    "will-o'-wisp", "genie", "gremlin", "demon", "incubus", "succubus", 
    "leprechaun", "boggart", "spriggan"
  ],
  "Prehistoric & Ancient": [
    "dinosaur"
  ],
  "Extraterrestrial": [
    "alien"
  ],
  "Botanical & Nature": [
    "mandrake"
  ],
  "Zodiacal": [
    "capricorn"
  ]
};

export const ALL_SETTING_TYPES = Object.values(SETTING_TYPE_CATEGORIES).flat();
export const ALL_CREATURE_TYPES = Object.values(CREATURE_TYPE_CATEGORIES).flat();

// Comprehensive ethnicity and cultural background options
export const ETHNICITY_CATEGORIES = {
  "European": [
    "British/English",
    "Irish", 
    "Scottish",
    "Welsh",
    "French",
    "German",
    "Italian",
    "Spanish",
    "Portuguese",
    "Dutch",
    "Belgian",
    "Swiss",
    "Austrian",
    "Polish",
    "Czech",
    "Slovak",
    "Hungarian",
    "Romanian",
    "Bulgarian",
    "Croatian",
    "Serbian",
    "Bosnian",
    "Albanian",
    "Greek",
    "Maltese",
    "Nordic/Scandinavian",
    "Norwegian",
    "Swedish",
    "Danish",
    "Finnish",
    "Icelandic",
    "Russian",
    "Ukrainian",
    "Belarusian",
    "Estonian",
    "Latvian",
    "Lithuanian"
  ],
  "East Asian": [
    "Chinese (Han)",
    "Japanese",
    "Korean",
    "Taiwanese",
    "Hong Kong Chinese",
    "Tibetan",
    "Mongolian",
    "Vietnamese",
    "Thai",
    "Cambodian/Khmer",
    "Laotian",
    "Burmese/Myanmar",
    "Filipino",
    "Indonesian",
    "Malaysian",
    "Singaporean",
    "Brunei"
  ],
  "South Asian": [
    "Indian (Northern)",
    "Indian (Southern)",
    "Pakistani",
    "Bangladeshi",
    "Sri Lankan",
    "Nepali",
    "Bhutanese",
    "Maldivian",
    "Afghan",
    "Punjabi",
    "Bengali",
    "Tamil",
    "Telugu",
    "Marathi",
    "Gujarati",
    "Kashmiri"
  ],
  "Middle Eastern": [
    "Arab",
    "Palestinian",
    "Lebanese",
    "Syrian",
    "Jordanian",
    "Iraqi",
    "Saudi Arabian",
    "Emirati",
    "Qatari",
    "Kuwaiti",
    "Bahraini",
    "Omani",
    "Yemeni",
    "Egyptian",
    "Moroccan",
    "Tunisian",
    "Algerian",
    "Libyan",
    "Persian/Iranian",
    "Turkish",
    "Kurdish",
    "Armenian",
    "Georgian",
    "Azerbaijani"
  ],
  "African": [
    "Nigerian",
    "Ghanaian",
    "Senegalese",
    "Malian",
    "Ivorian",
    "Burkinabe",
    "Kenyan",
    "Ethiopian",
    "Tanzanian",
    "Ugandan",
    "Rwandan",
    "South African",
    "Zimbabwean",
    "Botswanan",
    "Namibian",
    "Congolese",
    "Cameroonian",
    "Sudanese",
    "Eritrean",
    "Somali",
    "Liberian",
    "Sierra Leonean",
    "Gambian",
    "Guinean",
    "Malawian",
    "Zambian",
    "Mozambican",
    "Angolan",
    "Gabonese",
    "Equatorial Guinean",
    "Central African",
    "Chadian",
    "Mauritanian",
    "Djiboutian",
    "Swahili",
    "Yoruba",
    "Igbo",
    "Hausa",
    "Zulu",
    "Xhosa",
    "Amhara",
    "Oromo"
  ],
  "Latin American": [
    "Mexican",
    "Brazilian",
    "Colombian",
    "Argentinian",
    "Venezuelan",
    "Peruvian",
    "Ecuadorian",
    "Bolivian",
    "Chilean",
    "Paraguayan",
    "Uruguayan",
    "Guatemalan",
    "Honduran",
    "Salvadoran",
    "Nicaraguan",
    "Costa Rican",
    "Panamanian",
    "Cuban",
    "Dominican",
    "Puerto Rican",
    "Jamaican",
    "Trinidadian",
    "Barbadian",
    "Guyanese",
    "Surinamese",
    "Belizean",
    "Haitian"
  ],
  "Indigenous & Native": [
    "Native American (Cherokee)",
    "Native American (Navajo)",
    "Native American (Sioux)",
    "Native American (Apache)",
    "Native American (Iroquois)",
    "Native American (Pueblo)",
    "Native American (Chippewa)",
    "Native American (Choctaw)",
    "Native American (Creek)",
    "Native American (Seminole)",
    "Inuit",
    "First Nations (Cree)",
    "First Nations (Ojibwe)",
    "First Nations (Mi'kmaq)",
    "Métis",
    "Aboriginal Australian",
    "Torres Strait Islander",
    "Maori",
    "Pacific Islander (Samoan)",
    "Pacific Islander (Tongan)",
    "Pacific Islander (Fijian)",
    "Pacific Islander (Hawaiian)",
    "Maya",
    "Aztec/Nahuatl",
    "Inca/Quechua",
    "Guarani",
    "Mapuche"
  ],
  "Central Asian": [
    "Kazakh",
    "Uzbek",
    "Turkmen",
    "Kyrgyz",
    "Tajik",
    "Uyghur"
  ],
  "Mixed Heritage": [
    "Afro-Caribbean",
    "Anglo-Indian",
    "Eurasian",
    "Blasian (Black + Asian)",
    "Mestizo (Indigenous + European)",
    "Mulatto (African + European)",
    "Hapa (Half Asian Pacific)",
    "Creole",
    "Cape Coloured",
    "Pardo (Brazilian mixed)",
    "Multiracial",
    "Biracial"
  ],
  "Jewish Diaspora": [
    "Ashkenazi Jewish",
    "Sephardic Jewish",
    "Mizrahi Jewish",
    "Ethiopian Jewish",
    "Indian Jewish",
    "Bukharian Jewish"
  ],
  "Nomadic & Stateless": [
    "Roma/Romani",
    "Sinti",
    "Bedouin",
    "Tuareg",
    "Berber/Amazigh",
    "Kurmanji Kurdish",
    "Sorani Kurdish"
  ]
};

export const ALL_ETHNICITIES = Object.values(ETHNICITY_CATEGORIES).flat();

// Description types for the description generator
export const ALL_DESCRIPTION_TYPES = [
  // Objects & Items
  "armour", "weapon", "clothing", "uniform", "item", "wand", "book", "material", "potion", "furniture", "toy",
  
  // Health & Conditions
  "disease", "illness", "condition", "ailment", "poison", "mental_health", "pain", "dying", "medicine",
  
  // Environmental & Atmospheric
  "atmospheric", "climate", "weather", "storm", "sky", "environment", "natural_disaster", "apocalypse",
  
  // Cultural & Social
  "holiday", "tradition", "ritual", "religion", "society", "law", "culture", "ethnicity", "government", "organization", "military",
  
  // Skills & Abilities
  "martial_art", "spell", "cooking", "activity", "service", "trade",
  
  // Emotional & Psychological
  "tragedy", "trauma", "hysteria", "emotion", "aura",
  
  // Mystical & Supernatural
  "prophecy", "legend", "myth", "folklore", "deity",
  
  // Food & Drink
  "food", "drink", "taste", "cuisine",
  
  // Physical & Sensory Descriptions
  "smell", "hair", "eye", "nose", "facial_expression", "posture", "gait", "mouth", "general_physical", "smile", "facial_feature",
  
  // Character & Personality
  "personality", "character", "role", "title", "job",
  
  // Transportation & Vehicles
  "transportation", "vehicle", "flight",
  
  // Architecture & Buildings
  "architecture", "building",
  
  // Natural Elements & Sciences
  "element", "natural_law", "ecological", "anatomy", "morphology", "species", "crop", "resource",
  
  // Arts & Entertainment
  "music", "song", "poem", "dance", "game",
  
  // Communication & Language
  "language", "dialect", "accent", "document", "data",
  
  // Events & Conflicts
  "event", "conflict",
  
  // Technology
  "technology",
  
  // All Location Types (from setting generator) - using exact format from SETTING_TYPE_CATEGORIES
  ...ALL_SETTING_TYPES
];