import { db } from "../db";
import { bannedPhrases } from "@shared/schema";

const bannedPhrasesData = [
  // Forbidden Phrases
  { category: "forbidden", phrase: "provide/gain/offer valuable insights", isActive: true },
  { category: "forbidden", phrase: "indelible mark", isActive: true },
  { category: "forbidden", phrase: "unwavering commitment", isActive: true },
  { category: "forbidden", phrase: "stark reminder", isActive: true },
  { category: "forbidden", phrase: "sheds/shed light on", isActive: true },
  { category: "forbidden", phrase: "nuanced understanding", isActive: true },
  { category: "forbidden", phrase: "multifaceted nature/approach", isActive: true },
  { category: "forbidden", phrase: "complex interplay", isActive: true },
  { category: "forbidden", phrase: "intricate relationship", isActive: true },
  { category: "forbidden", phrase: "potential to revolutionize", isActive: true },
  { category: "forbidden", phrase: "transformative power", isActive: true },
  { category: "forbidden", phrase: "significant milestone/stride/turning point", isActive: true },
  { category: "forbidden", phrase: "unique blend/perspective", isActive: true },
  { category: "forbidden", phrase: "beacon of hope", isActive: true },
  { category: "forbidden", phrase: "pave the way", isActive: true },
  { category: "forbidden", phrase: "casting long shadows", isActive: true },
  { category: "forbidden", phrase: "hung heavy", isActive: true },
  { category: "forbidden", phrase: "at its core", isActive: true },
  { category: "forbidden", phrase: "delve into", isActive: true },
  { category: "forbidden", phrase: "to put it simply", isActive: true },
  { category: "forbidden", phrase: "key takeaway", isActive: true },
  { category: "forbidden", phrase: "from a broader perspective", isActive: true },
  { category: "forbidden", phrase: "generally speaking", isActive: true },
  { category: "forbidden", phrase: "arguably", isActive: true },
  { category: "forbidden", phrase: "to some extent", isActive: true },
  { category: "forbidden", phrase: "broadly speaking", isActive: true },
  { category: "forbidden", phrase: "rich tapestry", isActive: true },
  { category: "forbidden", phrase: "vibrant tapestry", isActive: true },
  { category: "forbidden", phrase: "opens new avenues", isActive: true },
  { category: "forbidden", phrase: "adds a layer of complexity", isActive: true },
  { category: "forbidden", phrase: "fostering a sense", isActive: true },
  { category: "forbidden", phrase: "plays a crucial/pivotal role", isActive: true },
  { category: "forbidden", phrase: "garnered significant attention", isActive: true },
  { category: "forbidden", phrase: "continues to inspire", isActive: true },
  { category: "forbidden", phrase: "seamless/seamlessly", isActive: true },
  { category: "forbidden", phrase: "scalable solution", isActive: true },
  { category: "forbidden", phrase: "cutting-edge", isActive: true },
  { category: "forbidden", phrase: "innovative", isActive: true },
  { category: "forbidden", phrase: "facilitate", isActive: true },
  { category: "forbidden", phrase: "bolster", isActive: true },
  { category: "forbidden", phrase: "streamline", isActive: true },
  { category: "forbidden", phrase: "revolutionize", isActive: true },
  { category: "forbidden", phrase: "leverage", isActive: true },
  { category: "forbidden", phrase: "utilize", isActive: true },
  { category: "forbidden", phrase: "optimize", isActive: true },
  { category: "forbidden", phrase: "navigate/navigating the landscape/complexities", isActive: true },
  { category: "forbidden", phrase: "showcasing", isActive: true },
  { category: "forbidden", phrase: "meticulous", isActive: true },
  { category: "forbidden", phrase: "intriguing", isActive: true },
  { category: "forbidden", phrase: "tapestry", isActive: true },
  { category: "forbidden", phrase: "comprehensive", isActive: true },
  { category: "forbidden", phrase: "testament", isActive: true },
  { category: "forbidden", phrase: "vibrant", isActive: true },
  { category: "forbidden", phrase: "dynamic", isActive: true },
  { category: "forbidden", phrase: "robust", isActive: true },
  { category: "forbidden", phrase: "let's dive in", isActive: true },
  { category: "forbidden", phrase: "take a dive into", isActive: true },
  { category: "forbidden", phrase: "dive into", isActive: true },
  { category: "forbidden", phrase: "deep dive into", isActive: true },
  { category: "forbidden", phrase: "embark on a journey/voyage", isActive: true },
  { category: "forbidden", phrase: "explore the world of", isActive: true },
  { category: "forbidden", phrase: "analyze", isActive: true },
  { category: "forbidden", phrase: "elevate", isActive: true },
  { category: "forbidden", phrase: "excels", isActive: true },
  { category: "forbidden", phrase: "unleash", isActive: true },
  { category: "forbidden", phrase: "harness", isActive: true },
  { category: "forbidden", phrase: "at the end of the day", isActive: true },
  { category: "forbidden", phrase: "it's worth noting that", isActive: true },
  { category: "forbidden", phrase: "it's important to note/consider/remember", isActive: true },
  { category: "forbidden", phrase: "ensure", isActive: true },
  { category: "forbidden", phrase: "it's essential to", isActive: true },
  { category: "forbidden", phrase: "there are a few considerations", isActive: true },
  { category: "forbidden", phrase: "cannot be overstated", isActive: true },
  { category: "forbidden", phrase: "ever-evolving", isActive: true },
  { category: "forbidden", phrase: "rapidly expanding/evolving", isActive: true },
  { category: "forbidden", phrase: "tailored", isActive: true },
  { category: "forbidden", phrase: "underpins", isActive: true },
  { category: "forbidden", phrase: "bustling", isActive: true },
  { category: "forbidden", phrase: "labyrinth", isActive: true },
  { category: "forbidden", phrase: "metropolis", isActive: true },
  { category: "forbidden", phrase: "game-changer", isActive: true },
  { category: "forbidden", phrase: "designed to enhance", isActive: true },
  { category: "forbidden", phrase: "daunting", isActive: true },
  { category: "forbidden", phrase: "the world of", isActive: true },
  { category: "forbidden", phrase: "in today's digital age/world", isActive: true },
  { category: "forbidden", phrase: "when it comes to", isActive: true },
  { category: "forbidden", phrase: "in the realm of", isActive: true },
  { category: "forbidden", phrase: "unlock/unveil the secrets", isActive: true },
  { category: "forbidden", phrase: "in the landscape of", isActive: true },
  { category: "forbidden", phrase: "in the dynamic world of", isActive: true },
  { category: "forbidden", phrase: "reverberate", isActive: true },
  { category: "forbidden", phrase: "remnant", isActive: true },
  { category: "forbidden", phrase: "nestled", isActive: true },
  { category: "forbidden", phrase: "gossamer", isActive: true },
  { category: "forbidden", phrase: "enigma", isActive: true },
  { category: "forbidden", phrase: "whispering", isActive: true },
  { category: "forbidden", phrase: "sights unseen", isActive: true },
  { category: "forbidden", phrase: "sounds unheard", isActive: true },
  { category: "forbidden", phrase: "a journey of", isActive: true },
  { category: "forbidden", phrase: "a multitude of", isActive: true },
  { category: "forbidden", phrase: "a plethora of", isActive: true },
  { category: "forbidden", phrase: "a testament to", isActive: true },
  { category: "forbidden", phrase: "actionable insights", isActive: true },
  { category: "forbidden", phrase: "ample opportunities", isActive: true },
  { category: "forbidden", phrase: "treasure trove", isActive: true },
  { category: "forbidden", phrase: "golden ticket", isActive: true },
  { category: "forbidden", phrase: "paradigm shift", isActive: true },
  { category: "forbidden", phrase: "game changer", isActive: true },
  { category: "forbidden", phrase: "disruptive innovation", isActive: true },
  { category: "forbidden", phrase: "groundbreaking", isActive: true },
  { category: "forbidden", phrase: "state-of-the-art", isActive: true },
  { category: "forbidden", phrase: "next-generation", isActive: true },
  { category: "forbidden", phrase: "thought leadership", isActive: true },
  { category: "forbidden", phrase: "best practices", isActive: true },
  { category: "forbidden", phrase: "synergy/synergistically", isActive: true },
  { category: "forbidden", phrase: "holistic/holistically", isActive: true },
  { category: "forbidden", phrase: "bandwidth", isActive: true },
  { category: "forbidden", phrase: "pain point", isActive: true },
  { category: "forbidden", phrase: "scalable", isActive: true },
  { category: "forbidden", phrase: "data-driven", isActive: true },
  { category: "forbidden", phrase: "customer-centric", isActive: true },
  { category: "forbidden", phrase: "mission-critical", isActive: true },
  { category: "forbidden", phrase: "foster innovation", isActive: true },
  { category: "forbidden", phrase: "driving innovation", isActive: true },
  { category: "forbidden", phrase: "unparalleled", isActive: true },
  { category: "forbidden", phrase: "unprecedented", isActive: true },
  { category: "forbidden", phrase: "revolutionary", isActive: true },
  { category: "forbidden", phrase: "transformative", isActive: true },
  { category: "forbidden", phrase: "strategic alignment", isActive: true },
  { category: "forbidden", phrase: "competitive landscape", isActive: true },
  { category: "forbidden", phrase: "deep understanding", isActive: true },
  { category: "forbidden", phrase: "fresh perspectives", isActive: true },
  { category: "forbidden", phrase: "new heights", isActive: true },
  { category: "forbidden", phrase: "reaching new heights", isActive: true },
  { category: "forbidden", phrase: "uncharted waters", isActive: true },
  { category: "forbidden", phrase: "the road ahead", isActive: true },
  { category: "forbidden", phrase: "the next frontier", isActive: true },
  { category: "forbidden", phrase: "the future of", isActive: true },
  { category: "forbidden", phrase: "captivating", isActive: true },
  { category: "forbidden", phrase: "remarkable", isActive: true },
  { category: "forbidden", phrase: "profound", isActive: true },
  { category: "forbidden", phrase: "invaluable", isActive: true },
  { category: "forbidden", phrase: "exemplary", isActive: true },
  { category: "forbidden", phrase: "commendable", isActive: true },
  { category: "forbidden", phrase: "thriving/thrive", isActive: true },
  { category: "forbidden", phrase: "flourishing", isActive: true },
  { category: "forbidden", phrase: "well-crafted", isActive: true },
  { category: "forbidden", phrase: "fundamentally", isActive: true },
  { category: "forbidden", phrase: "essentially", isActive: true },
  { category: "forbidden", phrase: "accordingly", isActive: true },
  { category: "forbidden", phrase: "consequently (when overused)", isActive: true },
  { category: "forbidden", phrase: "hence", isActive: true },
  { category: "forbidden", phrase: "thereby", isActive: true },
  { category: "forbidden", phrase: "thereof", isActive: true },
  { category: "forbidden", phrase: "therein", isActive: true },
  { category: "forbidden", phrase: "herein", isActive: true },
  { category: "forbidden", phrase: "heretofore", isActive: true },
  { category: "forbidden", phrase: "aforementioned", isActive: true },
  { category: "forbidden", phrase: "linchpin", isActive: true },
  { category: "forbidden", phrase: "epicenter", isActive: true },
  { category: "forbidden", phrase: "cornerstone", isActive: true },
  { category: "forbidden", phrase: "bedrock", isActive: true },
  { category: "forbidden", phrase: "fundamental", isActive: true },
  { category: "forbidden", phrase: "paramount", isActive: true },
  { category: "forbidden", phrase: "critical", isActive: true },
  { category: "forbidden", phrase: "crucial", isActive: true },
  { category: "forbidden", phrase: "essential", isActive: true },
  { category: "forbidden", phrase: "vital (when overused)", isActive: true },
  { category: "forbidden", phrase: "empower/empowering", isActive: true },
  { category: "forbidden", phrase: "enable/enabling", isActive: true },
  { category: "forbidden", phrase: "enhance/enhancing", isActive: true },
  { category: "forbidden", phrase: "amplify", isActive: true },
  { category: "forbidden", phrase: "augment", isActive: true },
  { category: "forbidden", phrase: "enrich/enriches", isActive: true },
  { category: "forbidden", phrase: "illuminate (figuratively)", isActive: true },
  { category: "forbidden", phrase: "digital transformation", isActive: true },
  { category: "forbidden", phrase: "cloud-based", isActive: true },
  { category: "forbidden", phrase: "AI-powered", isActive: true },
  { category: "forbidden", phrase: "blockchain-enabled", isActive: true },
  { category: "forbidden", phrase: "industry best practices", isActive: true },
  { category: "forbidden", phrase: "thought leaders", isActive: true },
  { category: "forbidden", phrase: "subject matter experts", isActive: true },
  { category: "forbidden", phrase: "value proposition", isActive: true },
  { category: "forbidden", phrase: "value-added", isActive: true },
  { category: "forbidden", phrase: "roi", isActive: true },
  { category: "forbidden", phrase: "kpis", isActive: true },
  { category: "forbidden", phrase: "deliverables", isActive: true },
  { category: "forbidden", phrase: "stakeholders", isActive: true },
  { category: "forbidden", phrase: "touchpoint", isActive: true },
  { category: "forbidden", phrase: "iteration", isActive: true },
  { category: "forbidden", phrase: "agile", isActive: true },
  { category: "forbidden", phrase: "sprint", isActive: true },
  { category: "forbidden", phrase: "scrum", isActive: true },
  { category: "forbidden", phrase: "mvp", isActive: true },
  { category: "forbidden", phrase: "poc", isActive: true },
  { category: "forbidden", phrase: "roadmap", isActive: true },
  { category: "forbidden", phrase: "deployment", isActive: true },
  { category: "forbidden", phrase: "implementation strategy", isActive: true },
  { category: "forbidden", phrase: "operational excellence", isActive: true },
  { category: "forbidden", phrase: "continuous improvement", isActive: true },
  { category: "forbidden", phrase: "process optimization", isActive: true },
  { category: "forbidden", phrase: "cost optimization", isActive: true },
  { category: "forbidden", phrase: "resource optimization", isActive: true },
  { category: "forbidden", phrase: "performance optimization", isActive: true },
  { category: "forbidden", phrase: "customer satisfaction", isActive: true },
  { category: "forbidden", phrase: "user engagement", isActive: true },
  { category: "forbidden", phrase: "user experience", isActive: true },
  { category: "forbidden", phrase: "brand awareness", isActive: true },
  { category: "forbidden", phrase: "market penetration", isActive: true },
  { category: "forbidden", phrase: "revenue growth", isActive: true },
  { category: "forbidden", phrase: "granular detail/level", isActive: true },
  { category: "forbidden", phrase: "high-level", isActive: true },
  { category: "forbidden", phrase: "low-level", isActive: true },
  { category: "forbidden", phrase: "drill down", isActive: true },
  { category: "forbidden", phrase: "glean insights", isActive: true },
  { category: "forbidden", phrase: "actionable", isActive: true },
  { category: "forbidden", phrase: "impactful", isActive: true },
  { category: "forbidden", phrase: "certainly here are/is", isActive: true },
  { category: "forbidden", phrase: "based on the information provided", isActive: true },
  { category: "forbidden", phrase: "it is worth noting", isActive: true },
  { category: "forbidden", phrase: "it is important to note", isActive: true },
  { category: "forbidden", phrase: "simply put", isActive: true },
  { category: "forbidden", phrase: "to clarify", isActive: true },
  { category: "forbidden", phrase: "with regards to", isActive: true },
  { category: "forbidden", phrase: "with a keen eye on", isActive: true },
  { category: "forbidden", phrase: "whilst", isActive: true },
  { category: "forbidden", phrase: "notwithstanding", isActive: true },
  { category: "forbidden", phrase: "nevertheless", isActive: true },
  { category: "forbidden", phrase: "moving forward", isActive: true },
  { category: "forbidden", phrase: "going forward", isActive: true },
  { category: "forbidden", phrase: "that being said", isActive: true },
  { category: "forbidden", phrase: "pivotal", isActive: true },
  { category: "forbidden", phrase: "underscore", isActive: true },
  { category: "forbidden", phrase: "realm", isActive: true },
  { category: "forbidden", phrase: "vast", isActive: true },
  { category: "forbidden", phrase: "keen", isActive: true },
  { category: "forbidden", phrase: "fancy", isActive: true },
  { category: "forbidden", phrase: "amongst", isActive: true },
  { category: "forbidden", phrase: "utmost", isActive: true },
  { category: "forbidden", phrase: "myriad", isActive: true },
  { category: "forbidden", phrase: "plethora", isActive: true },

  // Banned Transitions
  { category: "transition", phrase: "Firstly", isActive: true },
  { category: "transition", phrase: "Moreover", isActive: true },
  { category: "transition", phrase: "Furthermore", isActive: true },
  { category: "transition", phrase: "However", isActive: true },
  { category: "transition", phrase: "Therefore", isActive: true },
  { category: "transition", phrase: "Consequently", isActive: true },
  { category: "transition", phrase: "Subsequently", isActive: true },
  { category: "transition", phrase: "Specifically", isActive: true },
  { category: "transition", phrase: "Notably", isActive: true },
  { category: "transition", phrase: "Indeed", isActive: true },
  { category: "transition", phrase: "Thus", isActive: true },
  { category: "transition", phrase: "Essentially", isActive: true },
  { category: "transition", phrase: "Ultimately", isActive: true },
  { category: "transition", phrase: "Alternatively", isActive: true },
  { category: "transition", phrase: "Remember that", isActive: true },
  { category: "transition", phrase: "As well as", isActive: true },
  { category: "transition", phrase: "Despite", isActive: true },
  { category: "transition", phrase: "Although", isActive: true },
  { category: "transition", phrase: "Due to", isActive: true },
  { category: "transition", phrase: "Given that", isActive: true },
  { category: "transition", phrase: "In contrast", isActive: true },
  { category: "transition", phrase: "Even if", isActive: true },
  { category: "transition", phrase: "In order to", isActive: true },
  { category: "transition", phrase: "On the other hand", isActive: true },
  { category: "transition", phrase: "As previously mentioned", isActive: true },
  { category: "transition", phrase: "As a professional", isActive: true },
  { category: "transition", phrase: "To summarize", isActive: true },
  { category: "transition", phrase: "In summary", isActive: true },
  { category: "transition", phrase: "In conclusion", isActive: true },
  { category: "transition", phrase: "Promptly", isActive: true },
];

async function seedBannedPhrases() {
  console.log("Seeding banned phrases...");
  
  try {
    // Check if phrases already exist
    const existing = await db.select().from(bannedPhrases).limit(1);
    
    if (existing.length > 0) {
      console.log("Banned phrases already exist. Skipping seed.");
      return;
    }

    // Insert all phrases
    await db.insert(bannedPhrases).values(bannedPhrasesData);
    
    console.log(`Successfully seeded ${bannedPhrasesData.length} banned phrases.`);
  } catch (error) {
    console.error("Error seeding banned phrases:", error);
    throw error;
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedBannedPhrases()
    .then(() => {
      console.log("Seed complete!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seed failed:", error);
      process.exit(1);
    });
}

export { seedBannedPhrases };
